
%=============================================================
%   Author: Rafael Veras <rafaelmanoelveras@gmail.com>
%   Created at 06/23/2024
%=============================================================

function pchoice = choice_prob(EV, vf_myopic, beta)
%================================================================
%         Returns the probability of maintanance of each choice for each observed state,
%   conditional on an array of state/decision costs (generated by the myopic or forward-looking cost functions)
%================================================================
c       = vf_myopic(:,1);
tr      = vf_myopic(:,2);
pk      = exp(-c+beta*EV)./(exp(- tr - c(1,1) + beta*EV(1,1)) + exp(-c+beta*EV));
pchoice = pk;
end
        